include_guard(GLOBAL)

function(borealis_configure_android_application target)
    if (NOT ANDROID)
        return()
    endif ()
    if (NOT TARGET ${target})
        message(FATAL_ERROR "borealis Android application target does not exist: ${target}")
    endif ()

    get_target_property(_borealis_android_target_type ${target} TYPE)
    if (NOT _borealis_android_target_type STREQUAL "SHARED_LIBRARY")
        message(FATAL_ERROR "borealis Android application '${target}' must be created with add_library(... SHARED)")
    endif ()
    if (NOT AURORA_SDL3_JAVA_SOURCE_DIR OR NOT IS_DIRECTORY "${AURORA_SDL3_JAVA_SOURCE_DIR}/org/libsdl/app")
        message(FATAL_ERROR "borealis Android application needs Aurora's populated SDL Java source directory")
    endif ()
    if (NOT AURORA_ANDROID_JAVA_SOURCE_DIR OR NOT IS_DIRECTORY "${AURORA_ANDROID_JAVA_SOURCE_DIR}/dev/encounter/aurora")
        message(FATAL_ERROR "borealis Android application needs Aurora's Java platform sources")
    endif ()
    if (NOT ANDROID_ABI)
        message(FATAL_ERROR "borealis Android application needs ANDROID_ABI")
    endif ()
    if (NOT ANDROID_PLATFORM)
        message(FATAL_ERROR "borealis Android application needs ANDROID_PLATFORM")
    endif ()
    get_property(_borealis_android_version_name GLOBAL PROPERTY BOREALIS_ANDROID_VERSION_NAME)
    get_property(_borealis_android_version_code GLOBAL PROPERTY BOREALIS_ANDROID_VERSION_CODE)
    if (NOT _borealis_android_version_name OR NOT _borealis_android_version_code)
        message(FATAL_ERROR "borealis Android application needs a detected application version")
    endif ()

    set_target_properties(${target} PROPERTIES OUTPUT_NAME main)
    target_link_options(${target} PRIVATE "-Wl,-u,SDL_main" "-Wl,--build-id=sha1")

    set(_borealis_android_properties "${CMAKE_BINARY_DIR}/borealis-android.properties")
    file(GENERATE OUTPUT "${_borealis_android_properties}" CONTENT
            "# Generated by borealis_configure_android_application; do not edit.
borealis.nativeLibrary=$<TARGET_FILE:${target}>
borealis.androidAbi=${ANDROID_ABI}
borealis.androidPlatform=${ANDROID_PLATFORM}
borealis.sdlJavaDir=${AURORA_SDL3_JAVA_SOURCE_DIR}
borealis.auroraJavaDir=${AURORA_ANDROID_JAVA_SOURCE_DIR}
borealis.javaDir=${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../platforms/android/java
borealis.versionName=${_borealis_android_version_name}
borealis.versionCode=${_borealis_android_version_code}
            ")
    set(BOREALIS_ANDROID_PROPERTIES_FILE "${_borealis_android_properties}" PARENT_SCOPE)
    message(STATUS "borealis: Android application properties: ${_borealis_android_properties}")
endfunction()
